//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capacity
    {
        public Capacity()
        {
            this.Parkings = new HashSet<Parking>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdVehicle { get; set; }
        public Nullable<int> MaxCapacity { get; set; }
        public Nullable<int> MinCapacity { get; set; }
        public Nullable<int> CurrentCapacity { get; set; }
    
        public virtual TypeVehicle TypeVehicle { get; set; }
        public virtual ICollection<Parking> Parkings { get; set; }
    }
}
