//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public string NameContract { get; set; }
        public string Information { get; set; }
        public Nullable<int> IdOfficeStaff { get; set; }
        public Nullable<int> IdRenter { get; set; }
        public Nullable<int> TypeConTract { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual NV NV { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
