//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiGui
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public Nullable<int> IdPayment { get; set; }
        public Nullable<int> LicensePlates { get; set; }
    
        public virtual ThanhToan ThanhToan { get; set; }
        public virtual VehiclePark VehiclePark { get; set; }
    }
}
