//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiGui
    {
        public NguoiGui()
        {
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public string LicensePlates { get; set; }
        public string PlaceID { get; set; }
        public Nullable<int> IdVehicleType { get; set; }
        public string IdPlacePark { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Parking Parking { get; set; }
        public virtual TypeVehicle TypeVehicle { get; set; }
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
