//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV
    {
        public NV()
        {
            this.Contracts = new HashSet<Contract>();
            this.Operations = new HashSet<Operation>();
        }
    
        public int IdStaff { get; set; }
        public string HoVaTenNV { get; set; }
        public Nullable<System.DateTime> NgayAdd { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> LayOff { get; set; }
        public Nullable<System.DateTime> LayOffDate { get; set; }
        public Nullable<int> Absences { get; set; }
        public Nullable<int> IdSchedule { get; set; }
        public Nullable<int> IdPayment { get; set; }
        public Nullable<bool> isManage { get; set; }
        public Nullable<bool> isOfficeStaff { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
    }
}
