//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int IdActivity { get; set; }
        public Nullable<int> IdNV { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public string ProcessCategoryType { get; set; }
        public Nullable<System.DateTime> ImplementationDate { get; set; }
    
        public virtual NV NV { get; set; }
        public virtual TypeofOperation TypeofOperation { get; set; }
    }
}
