//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacePark
    {
        public string Id { get; set; }
        public Nullable<int> IdVehicleType { get; set; }
        public string IdPark { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Parking Parking { get; set; }
        public virtual TypeVehicle TypeVehicle { get; set; }
    }
}
