//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestingAbsence
    {
        public int id { get; set; }
        public int idStaff { get; set; }
        public Nullable<bool> accept { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> DateAccept { get; set; }
        public Nullable<int> idManager { get; set; }
    
        public virtual NV NV { get; set; }
    }
}
