//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleEmploy
    {
        public ScheduleEmploy()
        {
            this.NVs = new HashSet<NV>();
        }
    
        public int IdSchedule { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<System.DateTime> WorkingDay { get; set; }
        public Nullable<bool> Attendance { get; set; }
        public Nullable<int> IdTotalSche { get; set; }
    
        public virtual ICollection<NV> NVs { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
