//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public ThanhToan()
        {
            this.NguoiGuis = new HashSet<NguoiGui>();
            this.NVs = new HashSet<NV>();
        }
    
        public int IdPayment { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<int> IdTVehicle { get; set; }
    
        public virtual ICollection<NguoiGui> NguoiGuis { get; set; }
        public virtual ICollection<NV> NVs { get; set; }
        public virtual TypeVehicle TypeVehicle { get; set; }
    }
}
