//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeVehicle
    {
        public TypeVehicle()
        {
            this.Capacities = new HashSet<Capacity>();
            this.ThanhToans = new HashSet<ThanhToan>();
            this.VehicleParks = new HashSet<VehiclePark>();
        }
    
        public int IdVehicle { get; set; }
        public string NameVehicle { get; set; }
        public Nullable<float> UnitPrice { get; set; }
    
        public virtual ICollection<Capacity> Capacities { get; set; }
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
        public virtual ICollection<VehiclePark> VehicleParks { get; set; }
    }
}
