//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_license_plate_recognition.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclePark
    {
        public VehiclePark()
        {
            this.NguoiGuis = new HashSet<NguoiGui>();
        }
    
        public int LicensePlates { get; set; }
        public string PlaceID { get; set; }
        public Nullable<int> IdVehicleType { get; set; }
    
        public virtual ICollection<NguoiGui> NguoiGuis { get; set; }
        public virtual PlacePark PlacePark { get; set; }
        public virtual TypeVehicle TypeVehicle { get; set; }
    }
}
